channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - ipywidgets
  # - rise
  - notebook=6
  - jupyterlab=3
  - nodejs=14
  - yarn
  - pip:
    - jupyter-contrib-nbextensions
