channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  # - rise
  - notebook
  - jupyterlab
  - nodejs
  - yarn
  - pip:
    - jupyter-contrib-nbextensions
